# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

version: '3'
services:
  bridge:
    image: crustio/chainbridge:latest
    container_name: bridge
    environment:
      - KEYSTORE_PASSWORD=password
    command: --config /config/config.json --blockstore /blockstore
    volumes:
      - ./blockstore:/blockstore
      - ./config:/config
      - ./keys:/keys/
    network_mode: host